# week 7 Homework

In [1]:
# 1

In [2]:
import check
from check import fun
fun()

ModuleNotFoundError: No module named 'check'

In [3]:
# 2

In [10]:
def div(x,y):
    try:
        return x/y
    except ZeroDivisionError as e:
        print(e)


In [11]:
div(2, 4)

0.5

In [7]:
# 3 incomplete

In [14]:
class MyException(Exception):
    pass
def example_func(my_list: list):
    
    my_sum = 0
    sum_of_pairs = []

    try:
        if type(my_list) != list:
            return MyException("Typeeror for my_list. It must be a list")     
    
        for i in range(len(my_list)):
            sum_of_pairs.append(my_list[i] + my_list[i + 1])
            print("sum_of_pairs = ",sum_of_pairs)
    except IndexError as i:
        print(i)
    except Exception as e:
        print(e)
example_func("hi")
        
        

__main__.MyException('Typeeror for my_list. It must be a list')

In [11]:
# 4 

In [54]:
def Uppercontent(filename):
    try:
        myfile = open(filename, "r")
    except FileNotFoundError as a:
        print(a)
    except Exeption as e:
        print(e)
        for line in myfile:
            print(line.upper())
        myfile.close()  
Uppercontent("abc")

[Errno 2] No such file or directory: 'abc'


In [12]:
# 5

In [17]:
import numpy as np
a = np.random.randint(1, 10, (3,5))
print(a)

[[4 2 9 3 6]
 [8 1 1 9 9]
 [9 8 1 9 3]]


In [18]:
# 6

In [19]:
a = np.zeros(10)
a[5] = 3
print(a)

[0. 0. 0. 0. 0. 3. 0. 0. 0. 0.]


In [20]:
# 7

In [28]:
a = np.arange(3, 15)
a

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
# 8

In [33]:
a = np.array([1, 3, 5, 2, 4, 5])
b = a.reshape(3,2)
print(b)
print("\n")
c = a.reshape(2,3)
print(c)

[[1 3]
 [5 2]
 [4 5]]


[[1 3 5]
 [2 4 5]]


In [34]:
# 9 incomplete

In [25]:
import numpy as np
def np_func(a):
    while np.mean(a) >=5:
        a = np.divide(a, 2)
    else:
        print(a)

In [26]:
m = np.array([11, 3, 18, 30, 42, 12, 49])
np_func(m)

[1.375 0.375 2.25  3.75  5.25  1.5   6.125]


In [20]:
#10

In [49]:
def col(a = np.random.randint(1, 10, (5,4))):
    for i in range(4):
        print(a[...,i])
def row(a = np.random.randint(1, 10, (5,4))):
    for i in range(5):
        print(a[i,...])
        
col(),row()

[2 9 8 1 3]
[9 2 4 7 5]
[6 7 8 9 7]
[1 7 7 2 8]
[6 2 1 6]
[6 5 1 5]
[8 8 3 1]
[2 2 7 5]
[7 4 7 1]


(None, None)